#!/usr/bin/env python3
"""Generate a YouTube Community post draft from canonical episode metadata.

Writes `eng/youtube-posts/<slug>.md` so publishing can happen in Studio right
after the companion article/landing page ships.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO = Path("/Applications/DrAntoniou Projects/AgentCompanies")
CR = REPO / "companies/campaign-receipts"


def derive_article_url(meta: dict, slug: str) -> str:
    url = meta.get("article_url")
    if url:
        return str(url)
    return f"https://campaignreceipts.com/articles/{slug}"


def compose_post(title: str, article_url: str) -> str:
    return "\n".join(
        [
            f"# YouTube Community Post — {title}",
            "",
            "Status: draft generated by pipeline. Publish in YouTube Studio Community tab after article is live.",
            "",
            "## Post Copy",
            "",
            f"New receipt: {title}",
            "",
            f"Full story + sources: {article_url}",
            "",
            "More receipts: https://campaignreceipts.com",
            "SEALED archive: https://sealed2016.com",
            "Free weekly newsletter: https://campaignreceipts.com/weekly",
            "",
        ]
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--slug", required=True)
    args = ap.parse_args()

    slug = args.slug.strip()
    meta_path = CR / "eng" / "youtube-meta" / f"{slug}.json"
    if not meta_path.is_file():
        raise SystemExit(f"Missing metadata file: {meta_path}")

    meta = json.loads(meta_path.read_text())
    title = meta.get("title", slug)
    article_url = derive_article_url(meta, slug)

    out_dir = CR / "eng" / "youtube-posts"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{slug}.md"
    out_path.write_text(compose_post(title, article_url))
    print(f"✅ wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
