#!/usr/bin/env python3
"""
migrate-persona-bundles.py

Why: Paperclip's instruction bundles expect multiple markdown files (commonly
AGENTS.md + SOUL.md + HEARTBEAT.md + TOOLS.md). Our repo historically stored one
`personas/<role>.md` file.

What it does:
- For each `companies/<co>/personas/<role>.md` (excluding *.core.md / *.reference.md),
  create `companies/<co>/personas/<role>/` with:
    - AGENTS.md   (copy of the legacy file, NUL-stripped)
    - SOUL.md     (identity + role + lenses + safety-ish content)
    - HEARTBEAT.md (operating cadence + collaboration + done criteria)
    - TOOLS.md    (capabilities/integrations + least-privilege reminders)

It does NOT delete legacy files (plan requirement). It is safe to re-run: if the
bundle folder already exists with all four files, the role is skipped.

Usage:
  python3 infrastructure/scripts/migrate-persona-bundles.py --company healthbrew
  python3 infrastructure/scripts/migrate-persona-bundles.py --all-active
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]


@dataclass(frozen=True)
class Split:
    soul: str
    heartbeat: str
    tools: str


SECTION_RE = re.compile(r"^##\s+(\d+)\.\s+(.*)\s*$")


def _read_text(path: Path) -> str:
    b = path.read_bytes()
    b = b.replace(b"\x00", b"")
    return b.decode("utf-8", errors="replace")


def _split_agents_style(md: str) -> Split:
    """
    Split numbered sections like:
      ## 1. Identity ...
      ...
      ## 2. Role
    If not found, treat everything as AGENTS-only and keep other files short.
    """
    lines = md.splitlines()
    sections: dict[int, list[str]] = {}
    order: list[int] = []
    current: int | None = None

    for line in lines:
        m = SECTION_RE.match(line)
        if m:
            current = int(m.group(1))
            if current not in sections:
                sections[current] = []
                order.append(current)
            sections[current].append(line)
            continue
        if current is None:
            continue
        sections[current].append(line)

    if not sections:
        return Split(
            soul="# SOUL\n\n_(No numbered sections detected; refine manually.)_\n",
            heartbeat="# HEARTBEAT\n\n_(No numbered sections detected; refine manually.)_\n",
            tools="# TOOLS\n\n_(No numbered sections detected; refine manually.)_\n",
        )

    def join(nums: list[int]) -> str:
        out: list[str] = []
        for n in nums:
            out.extend(sections.get(n, []))
        return "\n".join(out).strip() + "\n"

    # Heuristic mapping tuned to our AGENTS.md 8-section template.
    # NOTE: Section 7 ("Safety and permissions") is intentionally treated as TOOLS-only,
    # because it is where integrations/credentials discipline lives in our templates.
    soul = join([n for n in order if n in (1, 2, 4)])
    heartbeat = join([n for n in order if n in (3, 6, 8)])
    tools = join([n for n in order if n in (7,)])

    # If tools is empty-ish, still provide a minimal scaffold.
    if len(tools.strip()) <= 20:
        tools = "# TOOLS\n\nSee `TOOLS.md` in this folder after manual pass.\n"

    return Split(soul=soul, heartbeat=heartbeat, tools=tools)


def _bundle_header(role: str, company: str) -> str:
    return (
        f"<!-- Paperclip persona bundle for `{company}` / `{role}` -->\n"
        f"<!-- Generated by infrastructure/scripts/migrate-persona-bundles.py -->\n\n"
    )


def migrate_company(company: str, dry_run: bool) -> int:
    personas_dir = REPO_ROOT / "companies" / company / "personas"
    if not personas_dir.exists():
        print(f"[skip] missing personas dir: {personas_dir}")
        return 0

    migrated = 0
    for md in sorted(personas_dir.glob("*.md")):
        name = md.name
        if name.endswith(".core.md") or name.endswith(".reference.md"):
            continue
        if name.lower() == "readme.md":
            continue

        role = md.stem
        bundle_dir = personas_dir / role
        targets = {
            "AGENTS.md": bundle_dir / "AGENTS.md",
            "SOUL.md": bundle_dir / "SOUL.md",
            "HEARTBEAT.md": bundle_dir / "HEARTBEAT.md",
            "TOOLS.md": bundle_dir / "TOOLS.md",
        }

        if bundle_dir.exists() and all(p.exists() for p in targets.values()):
            continue

        text = _read_text(md)
        split = _split_agents_style(text)

        if dry_run:
            print(f"[dry-run] would create: {bundle_dir}")
            migrated += 1
            continue

        bundle_dir.mkdir(parents=True, exist_ok=True)
        targets["AGENTS.md"].write_text(_bundle_header(role, company) + text, encoding="utf-8")
        targets["SOUL.md"].write_text(
            _bundle_header(role, company) + "# SOUL\n\n" + split.soul,
            encoding="utf-8",
        )
        targets["HEARTBEAT.md"].write_text(
            _bundle_header(role, company) + "# HEARTBEAT\n\n" + split.heartbeat,
            encoding="utf-8",
        )
        targets["TOOLS.md"].write_text(
            _bundle_header(role, company) + "# TOOLS\n\n" + split.tools,
            encoding="utf-8",
        )

        (bundle_dir / "README.md").write_text(
            "\n".join(
                [
                    f"# `{role}` persona bundle",
                    "",
                    "Canonical Paperclip files:",
                    "- `AGENTS.md`",
                    "- `SOUL.md`",
                    "- `HEARTBEAT.md`",
                    "- `TOOLS.md`",
                    "",
                    f"Legacy single-file persona remains at `../{role}.md` (not deleted).",
                    "",
                    "Next step (manual): update Paperclip `adapterConfig.instructionsFilePath` (or hire-time bundle)",
                    f"to point at `companies/{company}/personas/{role}/AGENTS.md` once validated in the dashboard.",
                    "",
                ]
            ),
            encoding="utf-8",
        )

        print(f"[ok] {company}/{role} -> {bundle_dir}")
        migrated += 1

    return migrated


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--company", help="Single company folder name under companies/")
    ap.add_argument(
        "--all-active",
        action="store_true",
        help="Migrate personas for active product companies + portfolio-hq",
    )
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    companies: list[str] = []
    if args.all_active:
        companies = [
            "concise",
            "nt-ministry",
            "healthbrew",
            "carstack",
            "portfolio-hq",
        ]
    elif args.company:
        companies = [args.company]
    else:
        ap.error("pass --company <name> or --all-active")

    total = 0
    for co in companies:
        total += migrate_company(co, dry_run=args.dry_run)

    print(f"done. migrated_roles={total}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
