'use client';

import { TrendingUp, ArrowUpRight } from 'lucide-react';
import { motion } from 'framer-motion';

export function PortfolioWidget() {
  return (
    <motion.div 
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      className="glass-panel p-6 mb-8 relative overflow-hidden"
    >
      <div className="absolute top-0 right-0 p-32 bg-success/5 rounded-full blur-3xl -z-10 transform translate-x-1/2 -translate-y-1/2"></div>
      
      <div className="flex justify-between items-center mb-6">
        <h2 className="font-display text-xl font-bold text-white">Your Portfolio</h2>
        <span className="text-xs font-mono bg-success/20 text-success px-2 py-1 rounded border border-success/30">
          PROFITABLE
        </span>
      </div>

      <div className="grid grid-cols-2 gap-6">
        <div>
          <div className="text-xs font-mono text-text-muted uppercase tracking-widest mb-1">Total Value</div>
          <div className="font-display text-4xl font-bold text-white tracking-tight">
            $14,250<span className="text-xl text-white/50">.00</span>
          </div>
        </div>
        <div className="flex flex-col items-end justify-center">
          <div className="flex items-center gap-2 text-success font-bold text-xl">
            <ArrowUpRight size={24} />
            +$2,450.50
          </div>
          <div className="text-sm font-mono text-success/80">
            +20.7% All Time
          </div>
        </div>
      </div>

      <div className="mt-6 pt-6 border-t border-white/5 flex items-center justify-between">
        <div className="text-sm text-text-muted font-medium">
          Edge generated by <span className="text-accent font-bold">Fable AI</span>
        </div>
        <button className="text-xs font-mono uppercase bg-white/5 hover:bg-white/10 border border-white/10 px-3 py-1.5 rounded transition-colors">
          View Screenshot
        </button>
      </div>
    </motion.div>
  );
}
